#!/usr/bin/env python3
"""Check every URL in korepetycje/materials.json.

Sends a GET with a browser User-Agent (several hosts reject urllib's default),
follows redirects, and reports anything that does not end in HTTP 200.

  - 403 from hosts in BOT_BLOCKING_HOSTS counts as "skipped", not a failure
    (matemaks.pl answers 403 to every non-browser client).
  - Network errors and timeouts are retried once before being reported.

Usage:
    python3 scripts/check_materials_links.py             # check, then open /
                                                          # update / close a
                                                          # GitHub issue via `gh`
    python3 scripts/check_materials_links.py --dry-run   # check, print only

The issue step needs the `gh` CLI plus GH_TOKEN / GITHUB_TOKEN with
`issues: write` (the workflow provides both). Exit code is 0 either way, so
the workflow only goes red when the script itself breaks.
"""
import argparse
import json
import subprocess
import sys
import urllib.error
import urllib.request
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path
from urllib.parse import urlparse

ROOT = Path(__file__).resolve().parent.parent
MATERIALS = ROOT / "korepetycje" / "materials.json"

UA = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/124.0 Safari/537.36"
)
TIMEOUT = 20
WORKERS = 8
ISSUE_TITLE = "Materiały: broken links"
BOT_BLOCKING_HOSTS = {"matemaks.pl", "www.matemaks.pl"}


def collect(data):
    """Return {url: [where, ...]} for every link in the data file."""
    urls = {}
    for subj in data["subjects"]:
        for sec in subj["sections"]:
            for link in sec["links"]:
                where = f'{subj["id"]} / {sec["title_pl"]} / {link["label"]}'
                urls.setdefault(link["url"], []).append(where)
    return urls


def fetch(url):
    """Return ('ok'|'skip'|'fail', detail)."""
    host = urlparse(url).hostname or ""
    last = ""
    for _ in range(2):
        req = urllib.request.Request(
            url,
            headers={
                "User-Agent": UA,
                "Accept": "text/html,application/pdf,*/*;q=0.8",
                "Accept-Language": "pl,en;q=0.8",
            },
        )
        try:
            with urllib.request.urlopen(req, timeout=TIMEOUT) as r:
                code = r.status
                r.read(1024)  # touch the body, then drop it
            if code == 200:
                return "ok", "200"
            last = str(code)
        except urllib.error.HTTPError as e:
            if e.code == 403 and host in BOT_BLOCKING_HOSTS:
                return "skip", "403 (bot-blocking host)"
            last = str(e.code)
            if e.code in (404, 410):
                break  # no point retrying
        except Exception as e:  # timeouts, DNS, TLS
            last = type(e).__name__ + ": " + str(e)[:80]
    return "fail", last


def gh(*args, check=True):
    return subprocess.run(["gh", *args], capture_output=True, text=True, check=check)


def update_issue(failures, total):
    found = gh(
        "issue", "list", "--state", "open", "--search", f'"{ISSUE_TITLE}" in:title',
        "--json", "number,title", check=False,
    )
    number = None
    if found.returncode == 0:
        for it in json.loads(found.stdout or "[]"):
            if it["title"] == ISSUE_TITLE:
                number = it["number"]
                break

    if not failures:
        if number:
            gh("issue", "close", str(number), "--comment",
               f"All {total} links OK on the latest run. Closing.")
            print(f"closed issue #{number}")
        else:
            print("no failures, no open issue")
        return

    lines = [
        f"{len(failures)} of {total} links in `korepetycje/materials.json` failed "
        "the weekly check.",
        "",
        "| Status | URL | Where |",
        "|---|---|---|",
    ]
    for url, status, wheres in failures:
        lines.append(f"| {status} | {url} | {'; '.join(wheres)} |")
    lines += ["", "Fix or drop the entries in `korepetycje/materials.json`, then run "
              "`python3 scripts/build_materials.py`.",
              "Generated by `.github/workflows/check-materials-links.yml`."]
    body = "\n".join(lines)
    if number:
        gh("issue", "edit", str(number), "--body", body)
        print(f"updated issue #{number}")
    else:
        gh("issue", "create", "--title", ISSUE_TITLE, "--body", body)
        print("created issue")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dry-run", action="store_true",
                    help="print results only; do not touch GitHub issues")
    args = ap.parse_args()

    data = json.loads(MATERIALS.read_text(encoding="utf-8"))
    urls = collect(data)
    items = sorted(urls)
    with ThreadPoolExecutor(max_workers=WORKERS) as pool:
        results = list(pool.map(fetch, items))

    failures, skipped, ok = [], 0, 0
    for url, (state, detail) in zip(items, results):
        if state == "ok":
            ok += 1
        elif state == "skip":
            skipped += 1
            print(f"SKIP  {detail:28} {url}")
        else:
            failures.append((url, detail, urls[url]))
            print(f"FAIL  {detail:28} {url}")
    print(f"\n{len(items)} unique URLs: {ok} ok, {skipped} skipped, {len(failures)} failed")

    if not args.dry_run:
        update_issue(failures, len(items))
    return 0


if __name__ == "__main__":
    sys.exit(main())
